package pta.arm3;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pascal.taie.World;
import pascal.taie.analysis.pta.PointerAnalysisResult;
import pascal.taie.config.AnalysisOptions;
import pascal.taie.ir.stmt.Stmt;
import pascal.taie.language.classes.JMethod;
import pascal.taie.language.type.ReferenceType;
import pta.baseline.cafd.WrapperDetector;
import pta.llm.LlmOracle;
import pta.llm.LlmQuery;
import pta.llm.LlmResponse;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Arm ③ (neuro-symbolic) — "CAFD done right": the LLM-as-PROPOSER stage of
 * sound per-callsite heap cloning.
 *
 * <h2>Thesis: "LLM proposes, sound logic disposes"</h2>
 * <p>The LLM is a <em>proposer only</em>. For each candidate method it answers
 * whether it believes the method is a fresh-allocation wrapper (a malloc-like /
 * factory method that returns a freshly-allocated object on every normally
 * returning path). This semantic judgment (from the method name / body) can
 * surface candidates a purely-syntactic value-flow heuristic ranks low or
 * misses.
 *
 * <p>The sound DISPOSER is B3's structural {@link WrapperDetector}, run against
 * a context-insensitive pre-analysis exactly as B3 does. A method is cloned iff:
 * <pre>
 *     m ∈ wrappers  ⇔  the LLM proposes m  AND  WrapperDetector confirms m
 * </pre>
 * The intersection is the load-bearing soundness gate:
 * <ul>
 *   <li>A WRONG LLM proposal (a non-wrapper — escaping side effect, or returns a
 *       shared/cached object) is REJECTED by the detector → not cloned → sound.</li>
 *   <li>A MISSED wrapper (LLM says NO) is simply not cloned → less precision,
 *       still sound.</li>
 * </ul>
 * Cloning only refines the heap abstraction (more abstract objects); it never
 * removes a real call edge or alias.
 *
 * <p>Contrast with B3, whose wrapper set is generated by its own heuristic
 * candidate generation: arm ③'s set is {@code detected ∩ proposed}.
 */
public final class LlmWrapperProposer {

    private static final Logger logger =
            LoggerFactory.getLogger(LlmWrapperProposer.class);

    /** Hard cap on the number of LLM queries (bounds cost on large programs). */
    private static final int MAX_QUERIES = 256;

    private LlmWrapperProposer() {
    }

    /**
     * Computes the confirmed wrapper set {@code detected ∩ proposed}.
     *
     * @param preResult sound CI pre-analysis result (drives both the candidate
     *                  enumeration and the structural detector)
     * @param options   analysis options (used to build the oracle)
     * @return the methods to clone per call site; empty when no oracle is
     *         configured (then arm ③ is a sound no-op equivalent to plain CI)
     */
    public static Set<JMethod> propose(PointerAnalysisResult preResult,
                                       AnalysisOptions options) {
        // Sound disposer: structural detection over the CI pre-analysis (B3).
        Set<JMethod> detected =
                WrapperDetector.detect(preResult, World.get().getClassHierarchy());

        LlmOracle oracle = ArmOracleFactory.fromOptions(options);
        if (oracle == null) {
            // No oracle => the LLM proposes nothing => no cloning (sound, == CI).
            logger.info("[arm3] no oracle configured — proposing no wrappers (CI-equivalent)");
            return Set.of();
        }

        // Broad candidate space: every reachable application method. The LLM may
        // propose ANY of them (including non-wrappers); the detector disposes.
        List<JMethod> candidates = preResult.getCallGraph()
                .reachableMethods()
                .distinct()
                .filter(LlmWrapperProposer::isAppMethod)
                .sorted((a, b) -> a.getSignature().compareTo(b.getSignature()))
                .limit(MAX_QUERIES)
                .collect(Collectors.toList());

        Set<JMethod> proposed = new LinkedHashSet<>();
        for (JMethod m : candidates) {
            LlmResponse resp = oracle.ask(
                    new LlmQuery("arm3-wrapper", buildPrompt(m), m.getName()));
            if (isYes(resp)) {
                proposed.add(m);
            }
        }

        // SOUND GATE: only LLM proposals that the detector confirms are cloned.
        Set<JMethod> confirmed = new LinkedHashSet<>();
        for (JMethod m : proposed) {
            if (detected.contains(m)) {
                confirmed.add(m);
            } else {
                logger.info("[arm3] REJECTED LLM proposal {}: WrapperDetector did not "
                        + "confirm it is a fresh-allocation wrapper (not cloned — sound)",
                        m.getSignature());
            }
        }
        logger.info("[arm3] LLM proposed {} method(s); detector confirmed {}; "
                        + "cloning {} (detected total = {})",
                proposed.size(), confirmed.size(), confirmed.size(), detected.size());
        return confirmed;
    }

    private static boolean isAppMethod(JMethod m) {
        return !m.isAbstract()
                && m.getDeclaringClass() != null
                && m.getDeclaringClass().isApplication()
                && m.getIR() != null;
    }

    private static boolean isYes(LlmResponse resp) {
        List<String> lines = resp.asLines();
        return !lines.isEmpty() && lines.get(0).equalsIgnoreCase("YES");
    }

    /**
     * Builds a bounded prompt asking whether {@code m} is a fresh-allocation
     * wrapper. (For offline mock oracles the body is unused; the oracle answers
     * from {@link LlmQuery#contextId()} = the method's simple name.)
     */
    private static String buildPrompt(JMethod m) {
        StringBuilder sb = new StringBuilder();
        sb.append("You are tuning a Java pointer analysis. Decide whether the ")
                .append("following method is a FRESH-ALLOCATION WRAPPER: a method ")
                .append("that, on every normally-returning path, returns a NEWLY ")
                .append("allocated object (a malloc-like / factory / make-style ")
                .append("method) with no path returning a pre-existing/shared ")
                .append("object and no escaping side effect.\n")
                .append("Answer with the single word YES or NO on the first line.\n\n")
                .append("Method: ").append(m.getSignature()).append('\n')
                .append("Body:\n");
        int n = 0;
        for (Stmt s : m.getIR().getStmts()) {
            sb.append("  ").append(s).append('\n');
            if (++n >= 60) {
                sb.append("  ...\n");
                break;
            }
        }
        if (!(m.getReturnType() instanceof ReferenceType)) {
            sb.append("(note: non-reference return type — cannot be a wrapper)\n");
        }
        return sb.toString();
    }
}
